### ISSUE TITLE
Confusing: useIC2Stuff=true still adds rotors to the game

### ISSUE THREAD

**Issue by Tetha** [Aroma1997/CompactWindmills#14]
Hi,

in resonantRise, useIC2Stuff is set to true for your mod. This works correctly, as no rotors are required for the windmills to output power and the rotors are not crafteable.

However, we just had a fair amount of confusion in the channel because the rotors are still added as items and findeable with NEI, but they are uncrafteable and not needed. 

I'd suggest to make the addition of the rotor items depend on the useIC2Stuff flag so the rotors aren't even provided as items if they are not needed. Additionally, though this might be a separate issue due to size, it would be cool if the rotors would be rendered all the time if useIC2Stuff is set to true so I can get the fancy visuals :)

**Comment by Aroma1997** [comment]
If I would not register the rotors if useIC2Stuff is disabled, I would break existing worlds, which already have Windmills with rotors in them. The Crafting Recipe is disabled, because you don't have to use them.
The Rotors are only renderd if useIC2Stuff is set to true if you have a rotor in the windmill. Why should I change that?
